services:
  - type: web
    name: flask-crm
    env: python
    pythonVersion: "3.11"
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crm-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

  - type: pserv
    name: crm-db
    env: postgres
    plan: free

